{% set version = "1.1.1" %}

package:
  name: tree-sitter-make
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tree-sitter-make/tree_sitter_make-{{ version }}.tar.gz
  sha256: ef394673ab83956dffb3986526f4c059082ff2d84c87f9da18ab30030f561b4c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - tree_sitter_make
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/alemuller/tree-sitter-make
  summary: Makefile grammar for tree-sitter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
